#  Create Numpy

In [1]:
pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\santo\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


# 2 - D Numpy Array

In [4]:
 b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# 3-D Numpy Array

In [5]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Float data type in Numpy

In [6]:
D = np.array([1,2,3], dtype = float)
print(D)

[1. 2. 3.]


# Range in Numpy

In [7]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.arange(1,9,2)

array([1, 3, 5, 7])

# Reshape 

In [9]:
v = np.arange(1,21).reshape(5,4)

print(v)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


# ones , Zeros

In [10]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Random

In [12]:
np.random.random((3,5))

array([[0.77853513, 0.33097051, 0.4469927 , 0.96444889, 0.95795301],
       [0.18939861, 0.94313706, 0.552939  , 0.80505933, 0.57389864],
       [0.64486477, 0.41859276, 0.85717845, 0.874816  , 0.6325814 ]])

# Linspace

In [19]:
np.linspace(10,20,5)

# 10 , 20 are range of np.array and 5 is elements in range

array([10. , 12.5, 15. , 17.5, 20. ])

In [20]:
np.linspace(10,20,5 , dtype = int)

array([10, 12, 15, 17, 20])

# Identity

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])