In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
a2[1,2]

6

In [4]:
a2[2,3]

11

In [5]:
a2[1,0]

4

# 3 - D  

In [6]:
a3[1,0,1] 
# first position is array
# secound position is Row
# third position is col

5

In [7]:
a3[0,1,0]

2

In [8]:
a3[0,0,0]

0

In [9]:
a3[1,1,0]

6

# slicing

In [10]:
a1[2:5]
# first position is start point
# secound position is end point

array([2, 3, 4])

In [11]:
a1[2:5:2]
# 

array([2, 4])

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a2[0,:]
# First position is Row

array([0, 1, 2, 3])

In [14]:
a2[:,2]
#secound position is col

array([ 2,  6, 10])

In [15]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [17]:
a2[0:3:2,1:4:2]

array([[ 1,  3],
       [ 9, 11]])

In [18]:
a2[1::2,::3]

array([[4, 7]])

In [19]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
# 3D Array

In [21]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [22]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [23]:
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
a3[0,1]

array([3, 4, 5])

In [25]:
a3[1,:,1]

array([10, 13, 16])

In [26]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [27]:
a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

# Advance Indexing

In [28]:
arr = np.random.randint(1,100,24).reshape(6,4)
arr


array([[68, 95, 82, 41],
       [87, 49, 49, 80],
       [ 9, 74,  9, 99],
       [17, 24, 33, 71],
       [59, 55, 85, 38],
       [92, 21, 35, 33]])

In [29]:
arr[[1,2,4,5]]

array([[87, 49, 49, 80],
       [ 9, 74,  9, 99],
       [59, 55, 85, 38],
       [92, 21, 35, 33]])

In [30]:
arr[:,[0,1,3]]

array([[68, 95, 41],
       [87, 49, 80],
       [ 9, 74, 99],
       [17, 24, 71],
       [59, 55, 38],
       [92, 21, 33]])

 # bool Indexing

In [31]:
arr[arr > 50]

array([68, 95, 82, 87, 80, 74, 99, 71, 59, 55, 85, 92])

In [32]:
arr[arr%2==0]

array([68, 82, 80, 74, 24, 38, 92])

In [33]:
arr[~(arr%7==0)]

array([68, 95, 82, 41, 87, 80,  9, 74,  9, 99, 17, 24, 33, 71, 59, 55, 85,
       38, 92, 33])

In [34]:
arr[(arr>50)&(arr%2==0)]

array([68, 82, 80, 74, 92])

In [35]:
arr>90

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [36]:
arr[arr>90]

array([95, 99, 92])