In [1]:
import numpy as np

In [3]:
a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


# DOT

In [4]:
np.dot(a,b)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

# VDOT

In [5]:
np.vdot(a,b)

564

# INNER

In [8]:
a1 = np.arange(5)
print(a1)
a2 = np.arange(5)
print(a2)
np.inner(a1,a2)


[0 1 2 3 4]
[0 1 2 3 4]


30

In [9]:
np.matmul(a,b)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

# numpy determinant
The determinant of the matrix can be calculated using the diagonal elements. The determinant of following 2 X 2 matrix

A       B
C       D

can be calculated as AD - BC.

The numpy.linalg.det() function is used to calculate the determinant of the matrix. Consider the following example.

In [15]:
d = np.arange(4).reshape(2,2)
print(d)

print("determinant:",np.linalg.det(d))

[[0 1]
 [2 3]]
determinant: -2.0
