In [1]:
import numpy as np

In [4]:
arr = np.arange(1,25).reshape(6,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [5]:
def sigmoid(arr):
    return 1/(1  + np.exp(-arr))
sigmoid(arr)

array([[0.73105858, 0.88079708, 0.95257413, 0.98201379],
       [0.99330715, 0.99752738, 0.99908895, 0.99966465],
       [0.99987661, 0.9999546 , 0.9999833 , 0.99999386],
       [0.99999774, 0.99999917, 0.99999969, 0.99999989],
       [0.99999996, 0.99999998, 0.99999999, 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])