In [1]:
import numpy as np

# Transpose

In [2]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2 = np.arange(1,13).reshape(3,4)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
np.transpose(a2)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [5]:
a2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# Ravel (converted to multi dimension into one dimension)

In [6]:
np.ravel(a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])