In [1]:
import numpy as np


In [2]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.full((2,3),"santosh")

array([['santosh', 'santosh', 'santosh'],
       ['santosh', 'santosh', 'santosh']], dtype='<U7')

In [5]:
np.empty((3)) 

array([1.14199214e+243, 2.43567338e-152, 1.27587193e-152])

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,6,7])
print(a)
print(b)
c= np.bitwise_or(a,b)
print("a and b" , a  in b)
print(c)

[1 2 3 4 5]
[1 2 3 6 7]
a and b True
[1 2 3 6 7]


In [64]:
arr = np.arange(1,25).reshape(6,4)
np.whare(arr>15,c,0)

AttributeError: module 'numpy' has no attribute 'whare'

In [22]:
arr[[1,2,3],[1,2,3]]

array([ 6, 11, 16])

In [29]:
a = np.sum(arr,axis = 0)
b = np.sum(arr,axis = 1)
print(a)
print(b)

[66 72 78 84]
[10 26 42 58 74 90]


In [33]:
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)

np.dot(a,b)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [56]:
a = np.array(["SANTOSH"])
b = np.array(["-"])
print(a,b)

['SANTOSH'] ['-']


In [58]:
np.char.split(a)

array([list(['SANTOSH'])], dtype=object)

In [61]:
np.char.join(a,b)

array(['-'], dtype='<U1')

In [71]:
np.eye(5,3,k = 0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
s = "python"
